# Generated by Django 2.2 on 2019-11-19 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20191119_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=10, max_digits=10, verbose_name='Precio'),
        ),
    ]
