# Generated by Django 2.2 on 2019-11-19 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20191119_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.FloatField(verbose_name='Precio'),
        ),
    ]
