# Generated by Django 2.2 on 2019-11-22 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20191121_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='galeriaLibros', verbose_name='imagen'),
        ),
    ]
