# Generated by Django 2.2 on 2019-11-22 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20191121_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(upload_to='galeriaLibros'),
        ),
    ]
