# Generated by Django 2.2 on 2019-11-20 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'contacto', 'verbose_name_plural': 'contactos'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='mensaje',
            field=models.CharField(max_length=250, verbose_name='mensaje'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='title',
            field=models.CharField(choices=[('Desarrollo Personal', 'Desarrollo Personal'), ('Bienestar Personal', 'Bienestar Personal'), ('Curso Meditacion', 'Curso Meditacion')], max_length=100),
        ),
    ]
